### ISSUE TITLE
Removed file puts scalafmt off

### ISSUE THREAD

**Issue by ennru** [scalameta/sbt-scalafmt#22]
I've sbt-scalafmt running on compile and work in a `~ test` cycle.

When I remove a file scalafmt is missing it so much that it fails:

```
7. Waiting for source changes in project p... (press enter to interrupt)
[info] Formatting 1 Scala sources...
[error] java.io.FileNotFoundException: /Users/....scala (No such file or directory)
...
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.$anonfun$withFormattedSources$1(ScalafmtPlugin.scala:92)
...
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.withFormattedSources(ScalafmtPlugin.scala:91)
[error] 	at org.scalafmt.sbt.ScalafmtPlugin$.formatSources(ScalafmtPlugin.scala:127)
```

After a `clean` everything is good again.

**Comment by ennru** [comment]
@poslegm Thank you for rapid fixing!
